version: "3.7"
services:
  substrate:
    image: parity/substrate:v2.0.0-alpha.3
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    expose:
      - 9933
      - 9944
      - 30333
    networks:
      gsrpc-network:
        ipv4_address: 172.42.0.2
    command: --dev --rpc-external --ws-external
  gsrpc-test:
    image: gsrpc-test
    build: .
    networks:
      gsrpc-network:
        ipv4_address: 172.42.0.99
    environment:
      - RPC_URL=ws://172.42.0.2:9944
    volumes:
      - "$PWD/shared:/go/src/github.com/zenghq3/go-substrate-rpc-client/shared"
networks:
  gsrpc-network:
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16
